project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: development
    development:
        host: http://127.0.0.1:8545/
        persist: false
        gas_limit: "auto"
        gas_buffer: 1
        gas_price: "auto"
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
    binance:
        host: https://rpc.ankr.com/bsc
        persist: false
        gas_limit: "auto"
        gas_buffer: 1
        gas_price: "auto"
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: max
        default_contract_owner: true
        cmd_settings: null
    live:
        gas_limit: auto
        gas_buffer: 1.1
        gas_price: auto
        max_fee: null
        priority_fee: null
        reverting_tx_gas_limit: false
        default_contract_owner: false

compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        remappings: 
    vyper:
        version: null

console:
    show_colors: false
    auto_suggest: true
    completions: true

reports:
    exclude_paths: null
    exclude_contracts: null
    only_include_project: true

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10
    phases:
        explicit: true
        reuse: true
        generate: true
        target: true
        shrink: true

autofetch_sources: false
dependencies: 
dev_deployment_artifacts: false
